### ISSUE TITLE
Size mismatch while loading 29.pth.tar for evaluation

### ISSUE THREAD

**Issue by akhilgakhar** [vignywang/IDC#1]
size mismatch for classifier_loc.0.weight: copying a param with shape torch.Size([200, 768, 3, 3]) from checkpoint, the
shape in current model is torch.Size([200, 256, 3, 3]).

**Comment by vignywang** [comment]
Please replace the latest networks/vgg_CUB.py

**Comment by akhilgakhar** [comment]
> Please replace the latest networks/vgg_CUB.py

Thanks, that works :)
